services:
  frontend:
    image: node:18-alpine
    container_name: nextjs
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    entrypoint: ["sh", "-c"]
    command: ["npm install && npm run dev"]
    environment:
      - NODE_ENV=development

  php:
    build: ./backend
    container_name: php
    volumes:
      - ./backend:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./backend:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: car
      MYSQL_ROOT_PASSWORD: morijyobi
      MYSQL_USER: user
      MYSQL_PASSWORD: morijyobi
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=morijyobi
      - MINIO_ROOT_PASSWORD=morijyobi123
    volumes:
      - ./minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ['server', '/data', '--console-address', ':9001']

networks:
  default:
    driver: bridge

volumes:
  db_data: