FROM php:8.0-fpm

# 必要なPHP拡張モジュールをインストール
RUN docker-php-ext-install mysqli pdo_mysql

# RUN mkdir -p /etc/mysql/conf.d

# COPY my.cnf /etc/mysql/conf.d/my.cnf

# RUN chmod 644 /etc/mysql/conf.d/my.cnf

# 作業ディレクトリを設定
WORKDIR /var/www/html